site_name: erik mkdocs
theme:
  name: material
  font:
    code: Roboto Mono
  features:
    - header.autohide

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
